version: "3.2"
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: project
      MYSQL_USER: project
      MYSQL_PASSWORD: project
      MYSQL_ROOT_PASSWORD: project
    ports:
      - "3306:3306"
    expose:
      - '3306'
